### ISSUE TITLE
AttributeError: module 'torch' has no attribute '_six'

### ISSUE THREAD

**Issue by programyy** [heroding77/fedavg_encrypt#1]
运行cifar时报错AttributeError: module 'torch' has no attribute '_six'，请问怎么解决？

**Comment by heroding77** [comment]
> 

torch版本问题，注意修改成和我环境相同的版本。

**Comment by heroding77** [comment]
> 



> 运行cifar时报错AttributeError: module 'torch' has no attribute '_six'，请问怎么解决？


torch版本问题，注意修改成和我环境相同的版本。
