### ISSUE TITLE
cifar10使用高斯差分隐私的问题

### ISSUE THREAD

**Issue by ttttC9** [heroding77/fedavg_encrypt#2]
RuntimeError: result type Float can't be cast to the desired output type Long

**Comment by heroding77** [comment]
是不是改代码了？那可能需要你检查一下数据格式的转换

**Comment by ttttC9** [comment]
只把conf.json的数据集换成了cifar10，模型换成了resnet18

**Comment by ttttC9** [comment]
在使用ResNet18或者有BN层的网络时，添加噪声会遇到这种情况batchnorm.num_batches_tracked，这时只需要把bn层的track_running_stats参数设为False即可，**self.batchnorm1 = nn.BatchNorm2d(64, track_running_stats=False)**
